exports.sanFrancisco = [
    "Outer Richmond",
    "Inner Richmond",
    "Russian Hill",
    "Chinatown",
    "Financial District",
    "Parkside",
    "Outer Sunset",
    "Inner Sunset",
    "Japantown",
    "The Haight",
    "Marina/Cow Hollow",
    "Lower Haight",
    "Locally-owned & operated",
    "Union Square",
    "Castro",
    "Western Addition",
    "Mission",
    "Lower Pacific Heights",
    "SoMa",
    "Lower Nob Hill",
    "Stonestown",
    "Crocker-Amazon",
    "Noe Valley",
    "Diamond Heights",
    "Laurel Heights",
    "Hayes Valley",
    "Bernal Heights",
    "North Beach/Telegraph Hill",
    "Tenderloin",
    "Potrero Hill",
    "Cole Valley",
    "Fisherman's Wharf",
    "Nob Hill",
    "Duboce Triangle",
    "NoPa",
    "Pacific Heights",
    "Portola",
    "Alamo Square",
    "Ingleside Terraces"
]

exports.berkeley = [
    "Oakland Chinatown",
    "Berkeley Hills",
    "Gourmet Ghetto",
    "Downtown Berkeley",
    "UC Area",
    "West Berkeley",
    "North Berkeley",
    "Elmwood",
    "Telegraph Ave",
    "Claremont",
    "Grand Lake",
    "Rockridge",
    "North Oakland",
    "Temescal",
    "Fourth Street",
    "South Berkeley",
    "East Solano Ave",
]

exports.sanMateo = [
    "",
    "Established in 1998",
    "Certified professionals"
]

